name: Docker Image CI

on:
  push:

    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run for any PRs.
  pull_request:

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      # Using checkout v1 since v2 fetches only a single commit by default, git diff-tree will have no output
      # Update to v2 when this PR is merged https://github.com/actions/checkout/pull/155 (subscribed)
      - uses: actions/checkout@v1

      - name: identify commited image directories
        id: get_updated_images
        run: |
          echo "::set-output name=directories::$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep images | awk -F '/' '{print $2}' | sort | uniq | xargs)"

      - name: build all relevant docker images
        run: |
          declare -a arr=(${{ steps.get_updated_images.outputs.directories }})
          echo "Found docker builds: $arr"

          export dockerRepo=docker.io

          for index in "${arr[@]}"
          do
            echo "building image: $index"
            cd $GITHUB_WORKSPACE/images/${index}
            ./build.sh
          done

      - name: log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login https://index.docker.io/v1/ --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: push images
        run: |
          declare -a arr=(${{ steps.get_updated_images.outputs.directories }})

          export dockerRepo=docker.io push=true

          for index in "${arr[@]}"
          do
            echo "pushing image: $index"
            cd $GITHUB_WORKSPACE/images/${index}
            ./build.sh
          done
